# filter config
# add in /etc/fail2ban/filter.d/rpp.conf
# example to ban requests to my.domain.com/.env & my.domain.com/.development.env

[Definition]
# default log format: %ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r
# example: Apr 21 10:13:56 my-lb haproxy[4109792]: 123.123.123.123:49074 [21/Apr/2026:17:13:56.063] fe_http~ be_frontend_80/my-node 0/0/0/116/182 404 56165 - - --NI 426/426/7/1/0 0/0 {my.domain.com} "GET /.env HTTP/1.1"
# "^.*haproxy\[[0-9]+\]: " matches the log prefix 
# => "Apr 21 10:13:56 my-lb haproxy[4109792]: "
# "<HOST>" matches "%ci" and is the variable for fail2ban for the ip we will ban 
# => "123.123.123.123"
# ":.* " matches everything starting from the client :port to the quoted request ":%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs "
# => ":49074 [21/Apr/2026:17:13:56.063] fe_http~ be_frontend_80/my-node 0/0/0/116/182 404 56165 - - --NI 426/426/7/1/0 0/0 {my.domain.com} "
# ""(GET |POST ).*(\.env|\.development\.env).* HTTP/1.1"$" matches the quoted request "%{+Q}r"
# => "GET /.env HTTP/1.1"
failregex = ^.*haproxy\[[0-9]+\]: <HOST>:.* "(GET |POST ).*(\.env|\.development\.env).* HTTP/1.1"$
ignoreregex =


# jail config
# add in /etc/fail2ban/jail.d/rpp.conf
# will ban the ip for 24h if filter hits 3 times in 1 min
[rpp]
port     = http,https
filter   = rpp
logpath  = /var/log/haproxy.log
maxretry = 3
findtime = 1m
bantime  = 24h
enabled  = true
# action will report to abuseipdb
action = %(action_)s
         %(action_abuseipdb)s[abuseipdb_category="19,21", abuseipdb_comment="[DOT FILES] crawler *.env*"]
